build:latest:
  image: fedora:latest
  script:
  - dnf upgrade --refresh -y
  - dnf install php php-devel sqlite php-xml php-mbstring php-pdo php-pgsql zip php-zip php-json php-gd php-ldap php-twig2 php-opcache php-mysqlnd php-pecl-pq composer node npm which -y
  - composer --version
  - cat .env.dist
  - cp .env.dist .env
  - composer install
  - node --version
  - npm --version
  - npm install -g yarn
  - yarn add node-sass
  - yarn install
  - pwd
  - mkdir -p /builds/kush/symfony-demo/var/data
  - touch /builds/kush/symfony-demo/var/data/blog.sqlite
  - touch /builds/kush/symfony-demo/var/data/blog_test.sqlite
  - ls -l /builds/kush/symfony-demo/var/data
  - bin/console doctrine:database:create