build:latest:
  image: fedora:latest
  script:
    - dnf upgrade --refresh -y
    - dnf install php php-xml php-mbstring php-pdo zip php-zip php-json php-gd php-ldap php-twig2 php-opcache php-mysqlnd php-pecl-pq composer -y
    - composer --version
    - composer install
    - ./vendor/bin/simple-phpunit
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - [ -s "$NVM_DIR/nvm.sh" ]
    - \. "$NVM_DIR/nvm.sh"
    - [ -s "$NVM_DIR/bash_completion" ]
    - \. "$NVM_DIR/bash_completion"
    - nvm --version
    - nvm install node
    - node --version
    - npm --version
    - npm install -g yarn
    - yarn install node-sass
    - yarn install