build:latest:
  image: php:latest
  script:
    - php --version
    - pwd
    - ls -a
    - apt-get update
    - apt-get install -y git zip php7.0-zip
    - curl --silent --show-error https://getcomposer.org/installer | php
    - mv composer.phar /usr/bin/composer
    - chmod +x /usr/bin/composer
    - composer --version
    - composer install
    - ./vendor/bin/simple-phpunit
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    - which nvm
    - nvm --version
    - nvm install node
    - node --version
    - npm --version
    - npm install -g yarn
    - yarn install